AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  birthday-reminder

  Sample SAM Template for birthday-reminder

Globals:
  Function:
    Timeout: 30

Resources:
  SaveBirthdayFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: save-birthday
      Handler: src/handlers/saveBirthday.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SaveBirthdayApi:
          Type: Api
          Properties:
            Path: /save-birthday
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/handlers/saveBirthday.ts
  
  BirthdayDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: birthdays
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: created
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: created
          KeyType: RANGE
  
  ScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule rule for birthday-reminder"
      ScheduleExpression: "cron(0 0 * * ? *)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt BirthdayReminderFunction.Arn
          Id: BirthdayReminderFunction
          Input: "{\"id\": \"birthday-reminder\"}"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt BirthdayReminderFunction.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduleRule.Arn
  
  BirthdayReminderFunction:
    Type: AWS::Serverless::Function
    Properties: 
      FunctionName: birthday-reminder
      Handler: src/handlers/birthdayReminder.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/handlers/birthdayReminder.ts

  LambdaDynamoDbWriteConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: SaveBirthdayFunction
      Destination:
        Id: BirthdayDatabase
      Permissions:
        - Write
