AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  birthday-reminder

  Sample SAM Template for birthday-reminder
  
Globals:
  Function:
    Timeout: 3

Resources:
  SaveBirthdayFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: save-birthday
      Handler: saveBirthday.lambdaHandler
      Runtine: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SaveBirthdayApi:
          Type: Api
          Properties:
            Path: /save-birthday
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/handlers/saveBirthday.ts
  
  BirthdayDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: birthdays
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: created
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: created
          KeyType: RANGE
